AWSTemplateFormatVersion: '2010-09-09'
Transform: [ AWS::Serverless-2016-10-31, SFNYAML ]


Resources:
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt ExecutionRole.Arn
      # DefinitionString: !Sub |
      #   {
      #     "StartAt": "Hello"
      #     "States": {
      #       "Hello": {
      #         "Type": "Task",
      #         "Resource": "${Function.Arn}",
      #         "End": true
      #       }
      #     }
      #   }
      DefinitionString:
        Comment: Parallel Example.
        StartAt: LookupCustomerInfo
        States:
          LookupCustomerInfo:
            Type: Parallel
            End: true
            Branches:
            - StartAt: LookupAddress
              States:
                LookupAddress:
                  Type: Task
                  Resource:
                    Fn::GetAtt:
                    - Function
                    - Arn
                  End: true
            - StartAt: LookupPhone
              States:
                LookupPhone:
                  Type: Task
                  Resource:
                    Fn::GetAtt:
                    - Function
                    - Arn
                  End: true
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: app.handler
      Runtime: python3.6
      Timeout: 10

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: executionrole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
